# Virgin River Forecasting 
In this notebook we will forecast river flows on the Virgin River in Utah. This is important since the Virgin River runs through Zion National Park and flash floods can be dangerous to hikers. We will leverage several models in Flow Forecast to get the best results and figure out the forecast.

In [ ]:
from google.colab import auth
from datetime import datetime
import os
auth.authenticate_user()
!git clone https://github.com/AIStream-Peelout/flow-forecast.git -b fixing_multitask_inform
!gsutil cp gs://predict_cfs/virgin_final1.csv virgin_final.csv 
!gsutil cp -r gs://predict_cfs/joined_final_3 .


Cloning into 'flow-forecast'...
remote: Enumerating objects: 16033, done.
remote: Counting objects: 100% (2890/2890), done.
remote: Compressing objects: 100% (902/902), done.
remote: Total 16033 (delta 2060), reused 2774 (delta 1973), pack-reused 13143
Receiving objects: 100% (16033/16033), 4.36 MiB | 20.97 MiB/s, done.
Resolving deltas: 100% (11611/11611), done.
Copying gs://predict_cfs/virgin_final1.csv...
/ [1 files][  9.2 MiB/  9.2 MiB]                                                
Operation completed over 1 objects/9.2 MiB.                                      
Copying gs://predict_cfs/joined_final_3/0101000040B_flow.csv...
Copying gs://predict_cfs/joined_final_3/0101007040B_flow.csv...
Copying gs://predict_cfs/joined_final_3/01010500FVE_flow.csv...
Copying gs://predict_cfs/joined_final_3/0101100040B_flow.csv...
\ [4 files][ 98.5 MiB/ 98.5 MiB]                                                
==> NOTE: You are performing a sequence of gsutil operations that may
run significantly 

In [ ]:
import pandas as pd
!gsutil cp gs://aistream-datasets/flowdb/09405500AZC_flow.csv .
df = pd.read_csv("09405500AZC_flow.csv")
df = df.dropna(subset=["hour_updated", "cfs", "p01m"])
df.to_csv("/content/joined_final_3/09405500AZC_flow.csv")

Copying gs://aistream-datasets/flowdb/09405500AZC_flow.csv...
/ [1 files][ 19.6 MiB/ 19.6 MiB]                                                
Operation completed over 1 objects/19.6 MiB.                                     


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2,4,7,8,9,18) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
df = pd.read_csv("09405500AZC_flow.csv")
df = df.dropna(subset=["hour_updated", "cfs", "p01m"])
df.sort_values(by=["hour_updated"])[1000:]

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2,4,7,8,9,18) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Unnamed: 0  Unnamed: 0_x  ...   cfs  height
1000         1005        1005.0  ...  52.7    0.31
1001         1006        1006.0  ...  52.7    0.31
1002         1007        1007.0  ...  55.5    0.34
1003         1008        1008.0  ...  55.5    0.34
1004         1009        1009.0  ...  56.4    0.35
...           ...           ...  ...   ...     ...
58155       58160       58153.0  ...  57.6    7.44
58156       58161       58154.0  ...  56.6    7.43
58157       58162       58155.0  ...  55.6    7.42
58158       58163       58156.0  ...  55.6    7.42
58159       58164       58157.0  ...  55.6    7.42

[57025 rows x 21 columns]

In [ ]:
import os
os.chdir('flow-forecast')
!pip install pandas --upgrade --force
!pip install -r  requirements.txt
!python setup.py develop
!mkdir data

     |████████████████████████████████| 11.3 MB 9.1 MB/s 
     |████████████████████████████████| 510 kB 75.3 MB/s 
     |████████████████████████████████| 15.7 MB 340 kB/s 
     |████████████████████████████████| 247 kB 70.9 MB/s 
  Attempting uninstall: six
    Found existing installation: six 1.15.0
    Uninstalling six-1.15.0:
      Successfully uninstalled six-1.15.0
  Attempting uninstall: pytz
    Found existing installation: pytz 2018.9
    Uninstalling pytz-2018.9:
      Successfully uninstalled pytz-2018.9
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.2
    Uninstalling python-dateutil-2.8.2:
      Successfully uninstalled python-dateutil-2.8.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled 

     |████████████████████████████████| 356 kB 8.6 MB/s 
     |████████████████████████████████| 22.3 MB 1.3 MB/s 
     |████████████████████████████████| 5.8 MB 22.0 MB/s 
     |████████████████████████████████| 1.7 MB 61.0 MB/s 
     |████████████████████████████████| 20.6 MB 1.2 MB/s 
     |████████████████████████████████| 816 kB 59.6 MB/s 
     |████████████████████████████████| 15.3 MB 57.6 MB/s 
     |████████████████████████████████| 1.0 MB 61.1 MB/s 
     |████████████████████████████████| 2.8 MB 55.6 MB/s 
     |████████████████████████████████| 133 kB 73.7 MB/s 
     |████████████████████████████████| 170 kB 57.2 MB/s 
     |████████████████████████████████| 97 kB 8.3 MB/s 
     |████████████████████████████████| 63 kB 2.2 MB/s 
     |████████████████████████████████| 3.1 MB 23.9 MB/s 
     |████████████████████████████████| 100 kB 13.5 MB/s 
     |████████████████████████████████| 121 kB 65.7 MB/s 
     |████████████████████████████████| 90 kB 12.1 MB/s 
     |█████████████

/usr/local/lib/python3.7/dist-packages/setuptools/dist.py:487: UserWarning: Normalizing '0.984dev' to '0.984.dev0'
  warnings.warn(tmpl.format(**locals()))
running develop
running egg_info
creating flood_forecast.egg-info
writing flood_forecast.egg-info/PKG-INFO
writing dependency_links to flood_forecast.egg-info/dependency_links.txt
writing requirements to flood_forecast.egg-info/requires.txt
writing top-level names to flood_forecast.egg-info/top_level.txt
writing manifest file 'flood_forecast.egg-info/SOURCES.txt'
package init file 'flood_forecast/__init__.py' not found (or not a regular file)
package init file 'flood_forecast/transformer_xl/__init__.py' not found (or not a regular file)
package init file 'flood_forecast/preprocessing/__init__.py' not found (or not a regular file)
package init file 'flood_forecast/da_rnn/__init__.py' not found (or not a regular file)
package init file 'flood_forecast/basic/__init__.py' not found (or not a regular file)
package init file 'flood_foreca

In [ ]:
!wandb login
os.environ['MODEL_BUCKET'] = "predict_cfs"
os.environ["ENVIRONMENT_GCP"] = "Colab"
os.environ["GCP_PROJECT"] = "gmap-997"

wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter: 
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


In [ ]:
import json
import os
import subprocess as subp
from flood_forecast.trainer import train_function
import traceback
from flood_forecast.long_train import split_on_letter

#!gsutil cp -r add_thing2 gs://predict_cfs/day_addition
def loop_through(data_dir:str, interrmittent_gcs=False, use_transfer=True, start_index=0, end_index=25): 
  """
  Function that makes and executes a set of config files
  This is since we have over 9k files.
  """
  if not os.path.exists("model_save"):
    os.mkdir("model_save")
  sorted_dir_list = sorted(os.listdir(data_dir))
  #total = len(sorted_dir_list)
  previous_gage = ""
  prev_config = {"pretrained_rivers":[]}
  for i in range(start_index, end_index):
      file_name = sorted_dir_list[i]
      station_id_gage = file_name.split("_flow.csv")[0]
      res = split_on_letter(station_id_gage)
      gage_id = res[0]
      station_id = res[1]
      file_path_name = os.path.join(data_dir, file_name)
      correct_file = None
      if use_transfer and len(os.listdir("model_save")) >0:
        print("Utilizing transfer learning")
        weight_files = filter(lambda x: x.endswith(".pth"), os.listdir("model_save"))
        paths = [] 
        for weight_file in weight_files:
             paths.append(os.path.join("model_save", weight_file)) 
        correct_file = max(paths, key = os.path.getctime)
        prev_config["pretrained_rivers"].append(previous_gage)
      sweep_full = wandb.sweep(wandb_sweep_config_full, project="github_aistream-peelout_flow-forecast")
      #sweep_id = "21i08e3p"
      wandb.agent(sweep_full, lambda:train_function("PyTorch", make_config_file(file_path_name, gage_id, station_id, correct_file, prev_config["pretrained_rivers"])))
      full_config = make_config_file(file_path_name, gage_id, station_id, correct_file, prev_config["pretrained_rivers"])
      try: 
        #model = train_function("PyTorch", config)
        print("temp disable")
      except Exception as e:
        print("An exception occured for: " + file_name_json)
        traceback.print_exc()
        print(e)
      previous_gage = gage_id

def make_config_file(flow_file_path, gage_id, station_id, weight_path=None, pretrained=[]):
  run = wandb.init(project="github_aistream-peelout_flow-forecast")
  wandb_config = run.config
  the_wandb_c = run.config
  the_config4 =  {"model_name": "Informer",
    "n_targets": 2,
    "use_decoder": True,
    "model_type": "PyTorch",
    "model_params": {
      "n_time_series":4,
      "dec_in":4,
      "c_out": 2,
      "seq_len":wandb_config["forecast_history"],
      "label_len":30, 
      "out_len":24,
      "factor":2
    },
    "dataset_params":
    {  "class": "TemporalLoader",
       "no_scale": False,
       "num_workers":4,
       "pin_memory": True,
       "training_path": flow_file_path,
       "validation_path": flow_file_path,
       "test_path": flow_file_path,
       "batch_size":wandb_config["batch_size"],
       "forecast_test_len":100,
       "forecast_history":wandb_config["forecast_history"],
       "forecast_length":24,
       "scaler": "StandardScaler",
       "train_start":1000,
       "train_end": 50000,
       "valid_start":50001,
       "valid_end": 57000,
       "sort_column": "hour_updated",
       "test_start": 57000,
       "test_end":58000,
       "target_col": ["cfs", "p01m"],
       "relevant_cols": ["cfs", "p01m", "tmpf", "dwpf"], 
       "interpolate":{
           "method":"back_forward_generic",
           "params":{
               "relevant_columns":["cfs", "tmpf", "p01m", "dwpf"]
           }

       },
     "feature_param":
     {
         "datetime_params":{
            "month": "numerical",
            "day": "numerical",
            "day_of_week": "numerical",
            "hour":"numerical"
         }
     }
    },
    "training_params":
    {
       "criterion":"MSE",
       "optimizer": "Adam",
       #"criterion_params":{"baseline_method":"mean"},
    "optim_params":{
       "lr": the_wandb_c["lr"]
    },
       "epochs": 10,
       "batch_size":wandb_config["batch_size"]
    },
    "early_stopping":{
        "patience":3
    },
    "GCS": True,
    "wandb":False,
    "sweep": True,
    "forward_params":{},
   "metrics":["MSE"],
   "inference_params":
   {     
         "datetime_start":"2020-05-31",
          "hours_to_forecast":336, 
          "num_prediction_samples": 20,
          "test_csv_path":flow_file_path,
          "decoder_params":{
            "decoder_function": "simple_decode", 
            "unsqueeze_dim": 1},
          "dataset_params":{
             "file_path": flow_file_path,
             "sort_column": "hour_updated",
             "scaling": "StandardScaler",
             "forecast_history": wandb_config["forecast_history"],
             "forecast_length":24,
             "relevant_cols": ["cfs", "tmpf", "p01m", "dwpf"],
             "target_col": ["cfs", "p01m"],
             "interpolate_param":{
                 "method":"back_forward_generic",
                 "params":{"relevant_columns":["cfs", "tmpf", "p01m", "dwpf"]}
                 }, 
            "feature_params":
        {
         "datetime_params":{
            "month": "numerical",
            "day": "numerical",
            "day_of_week": "numerical",
            "hour":"numerical"
         
     }
             }
          }
          } 
    }

      
  if weight_path:
    the_config4["weight_path"] = weight_path
  wandb.config.update(the_config4)
  print("config made")
  return the_config4
  
wandb_sweep_config_full = {
  "name": "Default sweep",
  "method": "grid",
  "parameters": {
        "batch_size": {
            "values": [32, 100, 250, 400]
        },
        "lr":{
            "values":[0.00001, 0.00001, 0.00005]
        },
        "forecast_history":{
            "values":[48, 96]
        }
        
}}

RuntimeError: ignored

In [ ]:
def make_config_file2(flow_file_path, gage_id, station_id, weight_path=None, pretrained=[]):

  the_config4 =  {"model_name": "SimpleLinearModel",
    "model_type": "PyTorch",
    "model_params": {
      "n_time_series":4,
      "seq_length":24,
    },
    "dataset_params":
    {  "class": "default",
       "no_scale": False,
       "num_workers":2,
       "pin_memory": True,
       "training_path": flow_file_path,
       "validation_path": flow_file_path,
       "test_path": flow_file_path,
       "forecast_test_len":100,
       "forecast_history":24,
       "forecast_length":1,
       "scaler": "StandardScaler",
       "train_start":1000,
       "train_end": 50000,
       "valid_start":50001,
       "valid_end": 57000,
       "sort_column": "hour_updated",
       "test_start": 57000,
       "test_end":58000,
       "target_col": ["cfs"],
       "relevant_cols": ["cfs", "p01m", "tmpf", "dwpf"], 
       "interpolate":{
           "method":"back_forward_generic",
           "params":{
               "relevant_columns":["cfs", "tmpf", "p01m", "dwpf"]
           }

       }
    },
    "training_params":
    {
       "criterion":"MSE",
       "optimizer": "SGD",
       #"criterion_params":{"baseline_method":"mean"},
    "optim_params":{
       "lr": 0.0001
    },
       "epochs": 10,
       "batch_size":200
    },
    "early_stopping":{
        "patience":3
    },
    "GCS": True,
    "sweep":True,
    "wandb":False,
    "forward_params":{},
   "metrics":["MSE"],
   "inference_params":
   {     
         "datetime_start":"2020-05-31",
          "hours_to_forecast":336, 
          "num_prediction_samples": 20,
          "test_csv_path":flow_file_path,
          "decoder_params":{
            "decoder_function": "simple_decode", 
            "unsqueeze_dim": 1},
          "dataset_params":{
             "file_path": flow_file_path,
             "sort_column": "hour_updated",
             "scaling": "StandardScaler",
             "forecast_history": 24,
             "forecast_length":1,
             "relevant_cols": ["cfs", "tmpf", "p01m", "dwpf"],
             "target_col": ["cfs"],
             "interpolate_param":{
                 "method":"back_forward_generic",
                 "params":{"relevant_columns":["cfs", "tmpf", "p01m", "dwpf"]}
                 }, 
             }
          }
    }

      
  if weight_path:
    the_config4["weight_path"] = weight_path
  print("config made")
  return the_config4

In [ ]:
import wandb
wandb.init()
trained_model = train_function("PyTorch", make_config_file2("/content/joined_final_3/09405500AZC_flow.csv", "virgin_river_09405500AZC", "AZC"))

config made
interpolate should be below
[]
Now loading /content/joined_final_3/09405500AZC_flow.csv
scaling now
interpolate should be below
[]
Now loading /content/joined_final_3/09405500AZC_flow.csv
scaling now
interpolate should be below
[]
Now loading /content/joined_final_3/09405500AZC_flow.csv
scaling now
Using Wandb config:
{}
Torch is using cuda
using 2
Pin memory set to true
running torch_single_train
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size([200, 1, 4])
torch.Size(

Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:974: UserWarning:

Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.



plotting with CI now
Now plotting final plots


In [ ]:
import wandb
sweep_full = wandb.sweep(wandb_sweep_config_full, project="github_aistream-peelout_flow-forecast")
wandb.agent(sweep_full, lambda:train_function("PyTorch", make_config_file("/content/joined_final_3/09405500AZC_flow.csv", "virgin_river_09405500AZC", "AZC")))
  

In [ ]:
trained_model.validation[0][0]

tensor([[-0.0767, -0.0839, -1.4344, -0.1110],
        [-0.0767, -0.0839, -1.6295, -0.5050],
        [-0.1048, -0.0839, -1.6016, -0.5706],
        [-0.1470, -0.0839, -1.7131, -0.7020],
        [-0.1599, -0.0839, -1.7688, -0.8333],
        [-0.1599, -0.0839, -1.7967, -0.8333],
        [-0.1740, -0.0839, -1.7131, -0.8990],
        [-0.1740, -0.0839, -1.7688, -0.8990],
        [-0.1740, -0.0839, -1.2672,  0.1517],
        [-0.1740, -0.0839, -0.9327,  0.0860],
        [-0.1868,  3.1812, -0.7655, -0.1110],
        [-0.1868, -0.0839, -0.7655,  0.0204],
        [-0.2009, -0.0839, -0.6819, -0.1766],
        [-0.2138, -0.0839, -0.6819, -0.3080],
        [-0.2138, -0.0839, -0.6819, -0.2423],
        [-0.2267, -0.0839, -0.6819, -0.3080],
        [-0.2267, -0.0839, -0.7098, -0.5050],
        [-0.2267, -0.0839, -0.9049, -0.3736],
        [-0.2267, -0.0839, -0.9885, -0.3736],
        [-0.2267, -0.0839, -1.2114, -0.3736],
        [-0.2267, -0.0839, -1.3508, -0.3736],
        [-0.2138, -0.0839, -1.4622

In [ ]:
res = trained_model.model(trial)

In [ ]:
trial = torch.zeros(1, 24, 4).to("cuda")
trial[:, 0:10, 1] = 0

In [ ]:
res

tensor([[0.1268]], device='cuda:0', grad_fn=<ViewBackward>)

In [ ]:
trial

tensor([[[  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.],
         [  0., 100.,   0.,   0.]]], device='cuda:0')

In [ ]:
x1 = x[0].unsqueeze(0).to(trained_model.device)
x2 = x[1].unsqueeze(0).to(trained_model.device)
y1= y[1].unsqueeze(0).to(trained_model.device)
y2 = y[0].unsqueeze(0).to(trained_model.device)

RuntimeError: ignored

In [ ]:
y2[0][:, -1] =30

RuntimeError: ignored

In [ ]:
res

RuntimeError: ignored

In [ ]:
trained_model.training.original_df

Unnamed: 0  Unnamed: 0.1  Unnamed: 0_x  ... day  day_of_week hour
0               0             5           5.0  ...  28            4   23
1               1             6           6.0  ...   1            5    0
2               2             7           7.0  ...   1            5    1
3               3             8           8.0  ...   1            5    2
4               4             9           9.0  ...   1            5    3
...           ...           ...           ...  ...  ..          ...  ...
58020       58155         58160       58153.0  ...   1            1   20
58021       58156         58161       58154.0  ...   1            1   21
58022       58157         58162       58155.0  ...   1            1   22
58023       58158         58163       58156.0  ...   1            1   23
58024       58159         58164       58157.0  ...   2            2    0

[58025 rows x 26 columns]

In [ ]:
trained_model.validation.original_df

Unnamed: 0  Unnamed: 0.1  Unnamed: 0_x  ... day  day_of_week hour
0               0             5           5.0  ...  28            4   23
1               1             6           6.0  ...   1            5    0
2               2             7           7.0  ...   1            5    1
3               3             8           8.0  ...   1            5    2
4               4             9           9.0  ...   1            5    3
...           ...           ...           ...  ...  ..          ...  ...
58020       58155         58160       58153.0  ...   1            1   20
58021       58156         58161       58154.0  ...   1            1   21
58022       58157         58162       58155.0  ...   1            1   22
58023       58158         58163       58156.0  ...   1            1   23
58024       58159         58164       58157.0  ...   2            2    0

[58025 rows x 26 columns]

In [ ]:
trained_model.validation.targ_scaler.inverse_transform(res.detach().cpu().numpy())

array([[[36.906853 ,  2.1357112],
        [34.202362 ,  2.155231 ],
        [30.138376 ,  2.1612527],
        [23.33542  ,  2.1809652],
        [15.480951 ,  2.2132566],
        [11.002726 ,  2.2551441],
        [ 6.8617578,  2.3023033],
        [ 6.0664926,  2.3308942],
        [ 9.702616 ,  2.2984607],
        [19.88262  ,  2.182052 ],
        [32.28048  ,  2.0611472],
        [44.020317 ,  2.0057492],
        [50.474903 ,  1.9901202],
        [56.954437 ,  1.9711663],
        [64.28146  ,  1.9692925],
        [66.70495  ,  1.9933916],
        [66.129135 ,  2.4444265],
        [57.148006 ,  2.4601433],
        [48.522694 ,  2.5093586],
        [47.19091  ,  2.5586538],
        [51.337204 ,  2.6051219],
        [51.6562   ,  2.6462836],
        [48.800888 ,  2.6711001],
        [48.94783  ,  2.6411579]]], dtype=float32)

In [ ]:
trained_model.validation.original_df[200:]

Unnamed: 0  Unnamed: 0.1  Unnamed: 0_x  ... day  day_of_week hour
200           200           205         205.0  ...   9            6    7
201           201           206         206.0  ...   9            6    8
202           202           207         207.0  ...   9            6    9
203           203           208         208.0  ...   9            6   10
204           204           209         209.0  ...   9            6   11
...           ...           ...           ...  ...  ..          ...  ...
58020       58155         58160       58153.0  ...   1            1   20
58021       58156         58161       58154.0  ...   1            1   21
58022       58157         58162       58155.0  ...   1            1   22
58023       58158         58163       58156.0  ...   1            1   23
58024       58159         58164       58157.0  ...   2            2    0

[57825 rows x 26 columns]

In [ ]:
x[0][:, 0:2]

tensor([[-0.9574, -0.0667],
        [-0.9574, -0.0667],
        [-0.9574, -0.0667],
        [-0.9574, -0.0667],
        [-1.0412, -0.0667],
        [-0.9574, -0.0667],
        [-0.9574, -0.0667],
        [-1.0532, -0.0667],
        [-1.0532, -0.0667],
        [-1.0532, -0.0667],
        [-1.0532, -0.0667],
        [-1.0532, -0.0667],
        [-1.0532, -0.0667],
        [-1.0532, -0.0667],
        [-1.0532, -0.0667],
        [-1.0532, -0.0667],
        [-0.6702, -0.0667],
        [-0.6702, -0.0667],
        [-0.6702, -0.0667],
        [-0.7659, -0.0667],
        [-0.7659, -0.0667],
        [-0.6702, -0.0667],
        [-0.7659, -0.0667],
        [-0.7659, -0.0667],
        [-0.7659, -0.0667],
        [-0.6702, -0.0667],
        [-0.6702, -0.0667],
        [-0.7659, -0.0667],
        [-0.7659, -0.0667],
        [-0.7659, -0.0667],
        [-0.7659, -0.0667],
        [-0.7779, -0.0667],
        [-0.6702, -0.0667],
        [-0.7779, -0.0667],
        [-0.6821, -0.0667],
        [-0.6821, -0